# Config file for Dynamics 365, and Authorized Azure App

# Resource URI, ie you CRM Instance
INSTANCE:
  PRODUCTION: <https://production.dynamics.com>
  SANDBOX: <https://sandbox.dynamics.com>
  API_VERSION: 9.1

# Username and Password to CRM Instance
DYNAMICS_CREDS:
  USERNAME: <username>
  PASSWORD: <password>

# Azure Tenant Auth Url
AZURE:
  APP_GUID: <app guid>

# Azure ClientID and Secret for Dynamics Api
APP:
  CLIENTID: <client id>
  CLIENTSECRET: <client secret>